CREATE DATABASE TGB
CREATE TABLE STUDENT (ID VARCHAR (30) NOT NULL, NAME VARCHAR (50) NOT NULL, AGE INT) 
CREATE TABLE CLASS ( ID VARCHAR (30) NOT NULL, NAME VARCHAR (50) NOT NULL)
CREATE TABLE SUBJECT ( ID VARCHAR (30) NOT NULL, NAME VARCHAR (50) NOT NULL )
ALTER TABLE STUDENT ADD PRIMARY KEY (ID)
ALTER TABLE CLASS ADD PRIMARY KEY (ID)
ALTER TABLE SUBJECT ADD PRIMARY KEY (ID)
INSERT INTO STUDENT VALUES (1, 'VICTOR', 14 )
INSERT INTO STUDENT VALUES (2, 'MICK', 13 )
INSERT INTO STUDENT VALUES (3, 'KELECHI', 15 )
INSERT INTO STUDENT VALUES (4, 'IKE', 14 )
INSERT INTO STUDENT VALUES (5, 'CHI', 16 )
INSERT INTO CLASS (ID, NAME) VALUES  (1, 'D'), ( 2, 'E'), (3,'F'), (4,'G'),(5,'H') 
INSERT INTO SUBJECT (ID, NAME) VALUES  (1, 'VI'), ( 2, 'AYO'), (3,'FEMI'), (4,'VERA'),(5,'RUBY') 
SELECT * FROM STUDENT
SELECT * FROM CLASS
SELECT * FROM SUBJECT
TRUNCATE TABLE STUDENT
TRUNCATE TABLE CLASS
TRUNCATE TABLE SUBJECT
INSERT INTO STUDENT VALUES (1, 'VICTOR', 14 )
INSERT INTO STUDENT VALUES (2, 'MICK', 13 )
INSERT INTO STUDENT VALUES (3, 'KELECHI', 15 )
INSERT INTO STUDENT VALUES (4, 'IKE', 14 )
INSERT INTO STUDENT VALUES (5, 'CHI', 16 )
INSERT INTO CLASS (ID, NAME) VALUES  (1, 'D'), ( 2, 'E'), (3,'F'), (4,'G'),(5,'H') 
INSERT INTO SUBJECT (ID, NAME) VALUES  (1, 'VI'), ( 2, 'AYO'), (3,'FEMI'), (4,'VERA'),(5,'RUBY') 










